### ISSUE TITLE
The datanommer queries are probably wrongly awarding badges to people

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedbadges#100]
Consider this scenario: I have made 1000 bodhi updates, each of which had at least one comment by someone. On each comment, a  `bodhi.update.comment` message is emitted. The `usernames` property of this message contains my username and the comment author's username, so I'm associated with the message in datanommer's `users` table.

When I make a comment on someone else's update, fedbadges will search datanommer for `bodhi.update.comment` messages related to my username, and will find all the comments made by other people on my updates, and therefore will think I made 1000 bodhi comments, and maybe award me a badge that I don't deserve.

So a lot of rules that currently have this sort of criteria:
```
criteria:
  datanommer:
      filter:
        topics:
        - "%(topic)s"     # The topic of the message that triggered us.
        users:
        - "%(msg.comment.author)s"
      operation: count
```
actually need an additional processing to make sure the returned message's `msg.comment.author` field matches the `users` field. This could be done in a lambda but feels redundant, this should actually be done automatically by fedbadges. But the simple `count` operation is not sufficient.
